Play travis
Otus-DevOps-2018-02/kobezzza_microservices pull request #2
Opened 2018-03-08 07:31 UTC by kobezzza

Добавил интеграцию с Travis. Настроил уведомления в Slack.

2018-03-17 22:34 UTC, sedovandrew requested changes
Андрей, я всё проверил. Единственная просьба, надо добавить изменения из мастер ветки в PR.

2018-03-18 06:58 UTC, kobezzza commented
@sedovandrew готово!

2018-03-20 01:48 UTC, sedovandrew approved these changes

2018-03-20 01:48 UTC, sedovandrew commented
Отлично!!

2018-03-20 09:03 UTC, merged